#!/bin/bash
#SBATCH -p general
#SBATCH -n 24
#SBATCH -N 1
#SBATCH --mem 30000
#SBATCH -t 2-0
#SBATCH -J test_align1234
#SBATCH --mail-type=ALL
#SBATCH --mail-user=nate_diehl@med.unc.edu
#SBATCH -o test_align1234.out
#SBATCH -e test_align1234.err

bbmap.sh threads=24 -Xmx30g in=/proj/derlab/projects/RNAseq/rawData/Panc_ERK_RAW/trimmed/TPC_0001_R1_L1_4_trimmed.fastq.gz in2=/proj/derlab/projects/RNAseq/rawData/Panc_ERK_RAW/trimmed/TPC_0001_R2_L1_4_trimmed.fastq.gz path=/proj/seq/data/hg38_UCSC/Sequence/BBMapIndex/ out=/proj/derlab/projects/RNAseq/rawData/Panc_ERK_RAW/aligned/TPC_0001_4_L1_aligned.bam maxindel=10000 intronlen=10 ambig=random qin=33 sam=1.4
bbmap.sh threads=24 -Xmx30g in=/proj/derlab/projects/RNAseq/rawData/Panc_ERK_RAW/trimmed/TPC_0001_R1_L2_4_trimmed.fastq.gz in2=/proj/derlab/projects/RNAseq/rawData/Panc_ERK_RAW/trimmed/TPC_0001_R2_L2_4_trimmed.fastq.gz path=/proj/seq/data/hg38_UCSC/Sequence/BBMapIndex/ out=/proj/derlab/projects/RNAseq/rawData/Panc_ERK_RAW/aligned/TPC_0001_4_L2_aligned.bam maxindel=10000 intronlen=10 ambig=random qin=33 sam=1.4
bbmap.sh threads=24 -Xmx30g in=/proj/derlab/projects/RNAseq/rawData/Panc_ERK_RAW/trimmed/TPC_0001_R1_L3_4_trimmed.fastq.gz in2=/proj/derlab/projects/RNAseq/rawData/Panc_ERK_RAW/trimmed/TPC_0001_R2_L3_4_trimmed.fastq.gz path=/proj/seq/data/hg38_UCSC/Sequence/BBMapIndex/ out=/proj/derlab/projects/RNAseq/rawData/Panc_ERK_RAW/aligned/TPC_0001_4_L3_aligned.bam maxindel=10000 intronlen=10 ambig=random qin=33 sam=1.4
bbmap.sh threads=24 -Xmx30g in=/proj/derlab/projects/RNAseq/rawData/Panc_ERK_RAW/trimmed/TPC_0001_R1_L4_4_trimmed.fastq.gz in2=/proj/derlab/projects/RNAseq/rawData/Panc_ERK_RAW/trimmed/TPC_0001_R2_L4_4_trimmed.fastq.gz path=/proj/seq/data/hg38_UCSC/Sequence/BBMapIndex/ out=/proj/derlab/projects/RNAseq/rawData/Panc_ERK_RAW/aligned/TPC_0001_4_L4_aligned.bam maxindel=10000 intronlen=10 ambig=random qin=33 sam=1.4